isl_blog_index:
    path: /blog
    defaults: { _controller: ISLBlogBundle:Blog:index }

isl_blog_lire:
    path: /blog/article/{id}
    defaults: { _controller: ISLBlogBundle:Blog:lire }
       
isl_blog_ajouter:
    path: /blog/ajouter
    defaults: { _controller: ISLBlogBundle:Blog:ajouter }

isl_blog_test_complexe:
    path: /blog/{annee}/{mois}/{categorie}.{format}
    defaults: { _controller: ISLBlogBundle:Blog:testComplexe, format: html }
    requirements:
        annee: \d{4}
        mois: \d{1,2}
        format: xml | rss | html