isl_blog_index:
    path: /{page}
    defaults: { _controller: ISLBlogBundle:Blog:index, page: 1 }
    requirements:
        id: \d*

isl_blog_voir:
    path: /article/{id}
    defaults: { _controller: ISLBlogBundle:Blog:voir }
    requirements:
        id: \d+

isl_blog_modifier:
    path: /modifier/{id}
    defaults: { _controller: ISLBlogBundle:Blog:modifer }
    requirements:
        id: \d+

isl_blog_ajouter:
    path: /ajouter
    defaults: { _controller: ISLBlogBundle:Blog:ajouter }
    
isl_blog_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: ISLBlogBundle:Blog:supprimer }
    requirements:
        id: \d+

#isl_blog_test_complexe:
#    path: /blog/{annee}/{mois}/{categorie}.{format}
#    defaults: { _controller: ISLBlogBundle:Blog:testComplexe, _format: html }
#    requirements:
#        annee: \d{4}
#        mois: \d{1,2}
#        _format: xml | rss | html