services:
    isl_blog.antimotsinterdits:
        class: ISL\BlogBundle\Services\AntiMotsInterdits
           
    article_repository:
        class: ISL\BlogBundle\Entity\ArticleRepository
        arguments: [ISL\BlogBundle\Entity\Article]
        factory_service: doctrine
        factory_method: getRepository