<?php

namespace ISL\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function selectAll(){
        return $this->createQueryBuilder('a')
                ->getQuery()
                ->getResult();
    }
    
    public function selectOne($id){
        $qb = $this->createQueryBuilder('a');
        
        $qb->where('a.id = :id');
        $qb->setParameter('id', $id);
        
        $res = $qb->getQuery()->getResult();
        
        if($res){
            // si la requete renvoit des resultats, on prend le premier
            // NB: d'autres méthodes existent $qb->getQuery()->getSingleResult()
            // qui lance une exception si il y a plus d'un résultat
            
            return $res[0];
        }else{
            return null;
        }
    }
    
    
    public function selectByAuteurOuTitre($auteur, $titre){
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.auteur = :auteur');
        $qb->orWhere('a.titre = :titre');
        $qb->setParameter('auteur', $auteur);
        $qb->setParameter('titre', $titre);
        
        return $qb->getQuery()->getResult();
    }
}
