<?php

namespace ISL\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    
    public function getCategoriesFiltrees(){
        $qb = $this->createQueryBuilder('cat');
        $qb->addSelect('cat');
        $qb->orderBy('cat.nom', 'ASC');
        
        return $qb;
    }
}
